using System;

namespace DefiningProperties{
    class Book{
        private string _name;
        private string _author;
        private int _pageCount;

        public Book(string name,string author,int pages){
            _name=name;
            _author=author;
            _pageCount=pages;
        }

        //Public Property
        public string Name{
            get{
                return _name;
            }
            set{
                _name=value;
            }
        }

        //Shorthand Public Property
        public string Author{
            get=>_author;
            set=>_author=value;
        }
        public int PageCount{
            get=>_pageCount;
            set=>_pageCount=value;
        }

        //Computed Property
        public string Desctiption{
            get=>$"{Name} by {Author}, {PageCount} pages";
        }

        //AutoGenerated Property
        public string ISBN{
            get;
            set;
        }
        public decimal Price{
            get;
            set;
        }
    }
}